version: "3"

services:

  microservice_app:
    container_name: microservice
#    restart: "never"
    build: .
    environment:
      - VIRTUAL_HOST=microservice.com
      - VIRTUAL_PORT=5000
    ports:
      - "5000:5000"
